### ISSUE TITLE
Error Loading Excel File in IDS Converter

### ISSUE THREAD

**Issue by nmartindorta** [c4rlosdias/ids_converter#10]
Error Loading Excel File in IDS Converter
This is a print screen of the error and attached excel file.
![image](https://github.com/c4rlosdias/ids_converter/assets/31612346/4edb4db9-d3fd-441e-ae79-a8b94a4b4e79)
[IDS_TEMPLATE-e1-v2.xlsx](https://github.com/c4rlosdias/ids_converter/files/15377332/IDS_TEMPLATE-e1-v2.xlsx)

**Comment by c4rlosdias** [comment]
Bug fixed
