### ISSUE TITLE
IFC4X3_ADD2 instead of IFC4X3?

### ISSUE THREAD

**Issue by MennoMekes** [c4rlosdias/ids_converter#11]
Hi,

When I set the Ifc version to IFC4X3 I get this message:

XMLSchemaValidationError: failed validating 'IFC4X3' with XsdEnumerationFacets(['IFC2X3', 'IFC4', 'IFC4X3_ADD2']): Reason: value must be one of ['IFC2X3', 'IFC4', 'IFC4X3_ADD2'] Schema component

Is IFC4X3_ADD2 not supported or is this just a matter of renaming IFC4x3 to IFC4x3_ADD2 as a choice?

**Comment by c4rlosdias** [comment]
fixed

**Comment by MennoMekes** [comment]
Hi Carlos,

Sorry for the late reply but I guess I'm the only one using this tool to chekc Ifc4X3_ADD2 models.
The conversion is actually not working becasue of the lowercase x in the template.
It should be IFC4X3_ADD2 instead of IFC4x3_ADD2.
