### ISSUE TITLE
CamelCase patterns

### ISSUE THREAD

**Issue by vitorhpmartins** [c4rlosdias/ids_converter#8]
Teacher, @c4rlosdias 

In the "entity name" column within the spreadsheet template, would it be possible to name the column as:

"Entity/Class"

Couldn't the other columns follow the CamelCase pattern from the IFC documentation itself? For example:

PredefinedType;
AttributeName.

Similarly to the "applicability" of the class, where in the current version we must put the entity name all in uppercase, wouldn't it also be possible to maintain the CamelCase pattern within the xlsx spreadsheet?

**Comment by c4rlosdias** [comment]
The IDs schema has its own standard that differs from the IFC standard. I'm following here the most faithful to the standard defined by the IDS
