### ISSUE TITLE
Error when using IDS Converter

### ISSUE THREAD

**Issue by aperezga** [c4rlosdias/ids_converter#9]
I am experiencing the following errors when trying to create an IDS file with IDS Converter:

TypeError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
```
File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script exec(code, module.__dict__)
File "/mount/src/ids_converter/pages/1_💾_Load_Excel_File.py", line 275, in <module> property = ids.Property(
```

I guess the first one is something related to Streamlit, but I have no idea what exactly is going on.

Thanks for your attention!

**Comment by rrdls** [comment]
@aperezga, Could you give more details on the steps you followed until you got this error? Did you use any specific files that you could share?

**Comment by aperezga** [comment]
@rrdls I get this error when I press the button "Convert to IDS", after loading the Excel file into the application. It does not matter which file I use. I have tried with two differente files: the Excel template provided on the web page, without making any changes, and the same template filled with two specifications.

I attach the my file.

[IDS_TEMPLATE_v2.xlsx](https://github.com/c4rlosdias/ids_converter/files/15377495/IDS_TEMPLATE_v2.xlsx)

**Comment by c4rlosdias** [comment]
bug fixed
